### ISSUE TITLE
Feature Request : Add date and time on registered video

### ISSUE THREAD

**Issue by TheMic** [interactionresearchstudio/NaturewatchCameraServer#101]
I was wondering if it was possible to put a date and time visible on the registered video.

Thanks in advance.

**Comment by mikevanis** [comment]
We have already been asked this. Adding a superimposed date and time in the video isn't something that aligns with the philosophy of the project, as it obscures the wildlife content captured.

**Comment by mikevanis** [comment]
Also, please use the provided template for feature requests, as it helps us handle these faster as a team. :)
