### ISSUE TITLE
Out of resource error

### ISSUE THREAD

**Issue by GaviG3** [interactionresearchstudio/NaturewatchCameraServer#110]
Hello,
I am using a Rasbery pi 4, 8gb, with the new cam 3.

I have downloaded the latest release and flashed sd card with etcher,
I can connect to wifi, but when I try connect to the sever I get the following error: attached image.

i have tried different platforms, mac, windows etc. could it be support for a pi cam 3?
![IMG_9612](https://github.com/interactionresearchstudio/NaturewatchCameraServer/assets/132746834/66479c1a-a148-483a-a557-1be2ea43f75b)

**Comment by GaviG3** [comment]
![image](https://github.com/interactionresearchstudio/NaturewatchCameraServer/assets/132746834/75b50732-0c99-408a-9b2a-99c4b266a756)


Got this when plugged into monitor

**Comment by andysheen** [comment]
answered here https://github.com/interactionresearchstudio/NaturewatchCameraServer/discussions/107
