### ISSUE TITLE
 no thumbnail (video and photo) in the gallery

### ISSUE THREAD

**Issue by belidi** [interactionresearchstudio/NaturewatchCameraServer#112]
Hello, My problem: no thumbnail (video and photo) in the gallery so it is impossible to read the recording or download it. the files are present in the /data/video or /data/photo folder
installed version 1.7, raspberry pi zero 2W, cam 1.3- 
 16GB SDHC SanDisk Ultra

**Comment by mikevanis** [comment]
Hi, can you share some screenshots? Is it only a few of them that don't have a thumbnail, or all of them?

**Comment by belidi** [comment]
all of them <img width="1478" alt="Screenshot 2024-03-13 at 14 56 33" src="https://github.com/interactionresearchstudio/NaturewatchCameraServer/assets/37706027/083adeaa-c5fe-4bce-bd28-0149d4532621"> <img width="1478" alt="Screenshot 2024-03-13 at 14 56 41" src="https://github.com/interactionresearchstudio/NaturewatchCameraServer/assets/37706027/84edd5ad-b1a8-4ed1-a1e3-ca1a3345b110"> <img width="428" alt="Screenshot 2024-03-13 at 14 57 51" src="https://github.com/interactionresearchstudio/NaturewatchCameraServer/assets/37706027/678ac12f-6557-4ebe-8702-63bc4cd69652">

but as you can see ( from "mc") the files are in the directory
