### ISSUE TITLE
Everything stops working after five minutes

### ISSUE THREAD

**Issue by dkallen78** [interactionresearchstudio/NaturewatchCameraServer#116]
**Describe the bug**
Might not be a bug, but after 5 or 10 minutes, all wireless connection ends and doesn't return.

**To Reproduce**
Follow the instructions on the website

**Expected behavior**
I had hoped that I would be able to check on the camera throughout the night, but after 5 or 10 minutes it stops broadcasting

**Screenshots**
nothing to screenshot since it doesn't broadcast.

**Desktop (please complete the following information):**
Windows 10
Firefox mobile and desktop
v?

**Smartphone (please complete the following information):**
Android 4a
Android
Firefox
v?

**Hardware**
Pi Zero 2 W
Camera Module 2 NoIR
v1.7
INIU 10,000 mAh power bank (https://www.amazon.com.mx/dp/B07CZDXDG8)
64GB SDcard

**Additional context**
I'm not sure what's happening. After about 5 or 10 minutes the Pi stops broadcasting whether I'm using the broadcasted WiFi network or connecting to my WiFi network

**Comment by andysheen** [comment]
Hi @dkallen78

We've had people in the past have issues when using SD cards with capacity of 64GB and above, so it could be that. I'd also try and run it off the Wall plug to see if it's any issues with using your power supply power. 

Hope that helps!
