### ISSUE TITLE
static_folder "static/client/build" doesn't exist

### ISSUE THREAD

**Issue by palto42** [interactionresearchstudio/NaturewatchCameraServer#21]
I tried to install this software as described in the README.md, but the connection to the server only responded with "404 Not Found". 

After reading through some code I found that the `static_folder` "static/client/build" which is assigned in `__init__.py` doesn't exist in the Docker build. Should this be created manually before running `docker-compose` or is it missing in the repository because `.gitignore` excludes `/build` folders?

If it should be build locally, then I would appreciate some instructions on how to do this.

**Comment by mikevanis** [comment]
The frontend of the software is built using React, so a build is necessary to compile the js files into HTML / CSS / JS. Our end goal is for this to be done with a multi-stage container setup, which we've got working on Pi 3's but unfortunately have been having some problems with on Pi Zero W. We're getting close to a solution, but for the time being, I've attached a compiled static/client/build directory for you to use so you can keep going. 

[build.zip](https://github.com/interactionresearchstudio/NaturewatchCameraServer/files/4437518/build.zip)

**Comment by palto42** [comment]
@mikevanis , thanks a lot for the explanation and the compiled build :+1:
