### ISSUE TITLE
Observations from Dean (when viewed on an iPad and an iPhone)

### ISSUE THREAD

**Issue by mrdeanbrown** [interactionresearchstudio/NaturewatchCameraServer#23]
Observations from Dean (when viewed on an iPad and an iPhone)

Photo / Exposure - In Manual the slider jumps back the left (1/30) wherever I try to slide it - the preview image is very dark. 

Video / Exposure - In Manual the slider jumps back the left (1/30) wherever I try to slide it - the preview image is very dark. 

Gallery / Video - the videos appear very long and thin in preview (iPad only)

Gallery / Video - When you refresh the video screen it refreshes to the photo screen.

Gallery / Video - Download all missing.

Gallery / Video - If I press and hold over a video it allows me to save a video still, but not the video itself.

Gallery / Video - Maybe I'm missing something but there is no obvious way to download the video

Gallery / Video - there is a sound / mute button on the video which seems a bit confusing considering that there's no sound playing.

Gallery / Video - the 'select ticks' look slightly wonky - where the white outer ring is offset from the blue circle.  Sometimes offset to the left (left column), Sometimes offset to the right (middle column), and sometimes correctly centred (right column).

Gallery / Photo - the photos appear very long and thin in preview (iPad only)

Gallery / Photo - Certain images are not shown as an image, but by text 'Captured by Naturewatch Camera'. This persists with a refresh. 

Gallery / Photo - Download all is missing.

Gallery / Photo - Change 'Press and hold to download' to 'Press and hold image for download options'? 

Gallert / Photo - the time and date look pretty accurate but I believe it's recording one hour behind

**Comment by mrdeanbrown** [comment]
Gallery / Video - Maybe I'm missing something but there is no obvious way to download the video

(I now see there's a button on the right of the video preview for this, but its quite subtle. Maybe there needs to be some instructions to make this more obvious)

**Comment by lovalle77** [comment]
Gallery / Video + Photo. When using the 'delete all' there is no confirmation for the action (eg. are you sure...?).  Is there a chance to include this?

**Comment by mikevanis** [comment]
I've moved all of these in separate issues, so closing this one. If you find anything else, create a new issue and we'll assign it and get working on it! 💯
