### ISSUE TITLE
Download All videos

### ISSUE THREAD

**Issue by mikevanis** [interactionresearchstudio/NaturewatchCameraServer#50]
Ability to download all videos with a single button.

**Comment by raphaelcoeffic** [comment]
This feature sounds great! But why just all videos, and not all photos?
(mass-downloading one category at a time is probably ok)

**Comment by mikevanis** [comment]
Download All Photos is pretty easy. It involves copying all photos to a temporary folder, zipping them, and sending them back to the client. For video, this involves potentially copying across gigabytes of video and zipping it all. A pi will struggle with that! So we need to find a different method for zipping up, without copying to a temp directory!

**Comment by raphaelcoeffic** [comment]
you could save the copy by sending the files directly into zip's input (like a pipe command).

**Comment by mikevanis** [comment]
That's a great idea! If you provide an example of the backend, I'm happy to work on the UI, as we had provisioned an interface element for this already. The client would send a JSON array of file names to zip up, and the python backend would need to pipe them into the zip file.

**Comment by raphaelcoeffic** [comment]
Deal!

**Comment by raphaelcoeffic** [comment]
Can we please help me with the UI in #74 ? I'm really awful with UI....

**Comment by mikevanis** [comment]
Just thinking about this now, you may run into issues still with piping, as presumably it still has to get loaded in RAM? So another option (just to keep options open for now) would be to fetch each piece of content and zip it up in JavaScript on the client side, which has a lot more RAM than the Pi. [This](https://yashodgayashan.medium.com/zip-files-in-react-30fb77fd6a58) would be a good starting point.

**Comment by raphaelcoeffic** [comment]
Not sure, as this basically knocks out the main here: the Pi Zero W has a dramatically slow Wifi link. Compression is here a good idea anyways ;-)

Concerning the RAM, no worry, I can test, as I have the small Pi Zero W, so if it works there, we're good to go. I believe the archive does not have to fit into memory. In fact, Zip files can be modified file by file, as far as I know. You can add single files, remove single files, all one by one. So I guess the pylib should do the same.

**Comment by raphaelcoeffic** [comment]
@mikevanis is that actually ok to introduce a dependency on python >= 3.5? Background is this: https://stackoverflow.com/questions/297345/create-a-zip-file-from-a-generator-in-python/55169752#55169752.

It seems Python 3.5 introduce support for real ZIP streaming, thus allowing to ZIP and stream all the videos (even very big).

**Comment by raphaelcoeffic** [comment]
Even better: https://github.com/BuzonIO/zipfly#zipfly
