### ISSUE TITLE
Sensitivity submenu does not open on some browsers

### ISSUE THREAD

**Issue by mikevanis** [interactionresearchstudio/NaturewatchCameraServer#68]
Report received from Jesus. Looks like the sensitivity submenu doesn't open on Windows Chrome. Will need to reproduce.

**Comment by crashmeplease** [comment]
Same issue on Android 10 Chrome

**Comment by crashmeplease** [comment]
Same issue also on Linux Mint Chrome and Firefox

**Comment by PlazzmiK** [comment]
Same problem tested on Windows 10 - Chrome / Firefox / Edge
