### ISSUE TITLE
Display thumbnail with overlaid video play button instead of blank video

### ISSUE THREAD

**Issue by mikevanis** [interactionresearchstudio/NaturewatchCameraServer#73]
In the gallery modal, a video is displayed as a white rectangle with a play button. It would be nice to display the thumbnail instead until the user presses the play button.

**Comment by mikevanis** [comment]
Could be done relatively easily [like this](https://stackoverflow.com/a/39231763/4039531).

**Comment by Vincent-Stragier** [comment]
@mikevanis if I understood it correctly it is the default behaviour now (see [edit](https://stackoverflow.com/a/50386123/10949679)), so this issue can be closed?

**Comment by mikevanis** [comment]
Correct! Just confirmed it's fixed on Android 12, Chrome, and Firefox.
