### ISSUE TITLE
Would you like to add  NaturewatchCameraServer to List of Distributions using CustomPiOS section?

### ISSUE THREAD

**Issue by guysoft** [interactionresearchstudio/NaturewatchCameraServer#76]
Hey all,
Was wondering if you would like to add NaturewatchCameraServer to the CustomPiOS list of distros using it:
https://github.com/guysoft/CustomPiOS#list-of-distributions-using-custompios

A PR is welcome :)

**Comment by andysheen** [comment]
Hey Guy,

Sure - i've made a PR here https://github.com/guysoft/CustomPiOS/pull/119 . 

Thanks for all the hard work!
