### ISSUE TITLE
Download keeps failing :'( - Could you provide an alternative download off of github?

### ISSUE THREAD

**Issue by winterstein** [interactionresearchstudio/NaturewatchCameraServer#92]
**Is your feature request related to a problem? Please describe.**
I've tried to download the image file a few times - the download fails part way through. This might be an issue with hosting a large file on github.

**Describe the solution you'd like**
I suggest having a copy of the file on a normal web server might be more reliable for downloads.

Thanks, Daniel

**Comment by mikevanis** [comment]
Hey, thanks for reporting. We'll have a look at this soon. At the moment we are running with a skeleton crew, and it's taking us a little longer to work through issues.

**Comment by mikevanis** [comment]
@wgaver @andygp2, is there a server available somewhere we can host a mirror of the latest Raspberry Pi image?

**Comment by mikevanis** [comment]
We don't currently have an available server to host this, so closing.
